// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4isCMMrqCgoUgqU9lYMIe1VqRx5vnUFM',
    appId: '1:441366519969:web:0df4f075b50cfdd1a350e0',
    messagingSenderId: '441366519969',
    projectId: 'mypskd',
    authDomain: 'mypskd.firebaseapp.com',
    storageBucket: 'mypskd.firebasestorage.app',
    measurementId: 'G-1R203ZD1TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnM5hh0jOvEAK7ace4uuJ5jvp9CrWq5Es',
    appId: '1:441366519969:android:9c6e849724fd4460a350e0',
    messagingSenderId: '441366519969',
    projectId: 'mypskd',
    storageBucket: 'mypskd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaRuE444RP4h0DnaMiupt9zrdAw2Wca6M',
    appId: '1:441366519969:ios:7e0d54787dd3e906a350e0',
    messagingSenderId: '441366519969',
    projectId: 'mypskd',
    storageBucket: 'mypskd.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
